name: Deploy
on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout repo code
      - uses: actions/checkout@v4

      # Setup gcloud
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCLOUD_CREDENTIALS}}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: mokstats

      # Setup python environment
      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install poetry env
        run: poetry install

      - name: Install poetry-plugin-export
        run: pip install poetry-plugin-export

      # Deploy
      - name: Collectstatic
        run: poetry run python manage.py collectstatic --noinput

      - name: Generate requirements.txt
        run: |
          poetry export --without-hashes --format requirements.txt --output ../requirements.txt
          cat ../requirements.txt

      - name: Deploy to gcloud
        run: gcloud app deploy app.prod.yaml

      # Database interaction
      - name: Start Cloud SQL Proxy
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.17.1/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          echo '${{secrets.GCLOUD_CREDENTIALS}}' > secrets.json
          ./cloud-sql-proxy mokstats:europe-west1:mokstats-prod --credentials-file secrets.json &

      - name: Migrate database, ensure superuser
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_NAME: mokstats-prod
          DB_USER: mokstats-prod
          DB_PASSWORD: ${{secrets.GCLOUD_PROD_DB_PASSWORD}}
          DJANGO_SUPERUSER_PASSWORD: ${{secrets.DJANGO_SUPERUSER_PASSWORD}}
        run: |
          poetry run python manage.py migrate
          poetry run python manage.py createsuperuser --username andre --email andre.okul@gmail.com --no-input || true

      # Clean up (source: https://stackoverflow.com/a/66911696/686131)
      - name: Delete old app engine versions
        run: gcloud app versions list --service default --format="value(version.id)" --sort-by="~version.createTime" | tail -n +6 | xargs -r gcloud app versions delete --quiet
